name: opendyn_dart
description: An OpenDyn JSON Spec Parser, fromJson and toJson
version: 0.1.0
repository: https://github.com/LiteVar/opendyn_dart

environment:
  sdk: ^3.6.1

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.24.0
